### ISSUE TITLE
feat: Add flutter `Stack` support in `Mirai`

### ISSUE THREAD

**Issue by i-asimkhan** [Securrency-OSS/mirai#113]
**Description**
According to official documentation, Stack is a widget that positions its children relative to the edges of its box.

This class is useful if you want to overlap several children in a simple way, for example having some text and an image, overlaid with a gradient and a button attached to the bottom.

**Additional Context**

For more details please visit the official documentation [ here ](https://api.flutter.dev/flutter/widgets/Stack-class.html)

**Comment by i-asimkhan** [comment]
@loud-at-heart Would you like to take this ?

**Comment by loud-at-heart** [comment]
@i-asimkhan Sure will give this a shot
