### ISSUE TITLE
What the documentation means about 'ExampleScreenParser'? 

### ISSUE THREAD

**Issue by rsalmeron-disney** [Securrency-OSS/mirai#161]
void main() async {
  final dio = Dio()

  await Mirai.initialize(
    parsers: const [
      ExampleScreenParser(),
    ],
    dio: dio,
  );

  runApp(const MyApp());
}

In this example in parsers requires an ExampleScreenParser, what would be an example of this? 

Thanks!!!!

**Comment by divyanshub024** [comment]
Hey @rsalmeron-disney!! 

Mirai allows us to create and use our own custom parser/widgets. This is example is showing that.

**Comment by divyanshub024** [comment]
Hey @rsalmeron-disney, I'm closing this issue now. Please reopen if the question still exists.
