### ISSUE TITLE
feat: Add support for `RefreshIndicator` in `Mirai`

### ISSUE THREAD

**Issue by RodolfoSilva** [Securrency-OSS/mirai#173]
**Description**

Currently we don't have the ability to refresh the current route or a list. I think we can add a support to `RefreshIndicator` to allow the user refresh the list or the current page.
 
**Requirements**

- [ ] Support `RefreshIndicator`
- [ ] Support refresh the current router

**Additional Context**

With this feature, the user will be able any time to pull the page to refresh the content displayed, showing a indicator on the top of the page.
A video example how we can use the `RefreshIndicator` today, in a regular app. https://www.youtube.com/watch?v=2h1yZARPC5U

What do you think about this feature @i-asimkhan, @divyanshub024? Do you have any suggestion how can we do that? Could this this be done with the addition of Signals #164?

**Comment by i-asimkhan** [comment]
I think we can add this once #56 and #150 are added because as far as refresh is concerned we need a way to load data from the API.

**Comment by divyanshub024** [comment]
I agree. We need to have solid Network request support first.
