### ISSUE TITLE
feat: Replace `Image.network` with CachedNetworkImage.

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#255]
**Description**

This issue is set to open discussion for replacing `Image.network` with [cached_network_image](https://pub.dev/packages/cached_network_image).

This will add a dependency on a third-party package but it will help a lot in reducing the network load.

**Comment by vkmaxcooldude** [comment]
Hey @divyanshub024, can you assign this issue to me?

**Comment by divyanshub024** [comment]
Thank you @vkmaxcooldude, I've assigned the issue to you :)
