### ISSUE TITLE
feat: Add support to Chip Widget

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#256]
**Description**

Add support to Flutter Chip Widget

**Requirements**

- [ ] Create Mirai Chip Parser
- [ ] Add a chip widget example 

**Additional Context**

[Add any other context or screenshots about the feature request go here.](https://api.flutter.dev/flutter/material/Chip-class.html)

**Comment by iampranabray** [comment]
I want to take this up.

**Comment by divyanshub024** [comment]
@iampranabray Thank you, for taking this up. I've assigned the issue to you.
