### ISSUE TITLE
feat: A new way to redefine how we declare`EdgeInsets`. 

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#260]
**Description**

Right now there is only one way to define MiraiEdgeInsets.

```
              "padding": {
                "top": 8,
                "left": 12,
                "right": 12,
                "bottom": 8
              }
```

There should be a better to define it like.

1. For giving same padding to all.

```
"padding`: 8,
```

2. Define padding for all dir.

```
"padding": [8, 12, 12, 8]
```

This way it will be easier to define padding and make the JSON smaller.

**Comment by superiorsd10** [comment]
Hello @divyanshub024 👋

I want to work on this issue, so please consider assigning it to me. 

Thank you,

**Comment by divyanshub024** [comment]
Hey @superiorsd10 👋

I've assigned it to you. Looking forward to see your contribution 🚀
