### ISSUE TITLE
feat: Add a search bar in Mirai Gallery

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#282]
**Description**

Add a search bar on the Mirai Gallery home page. This will allow us to search the examples from the gallery.

<img width="402" alt="Screenshot 2024-03-02 at 12 51 01 PM" src="https://github.com/Securrency-OSS/mirai/assets/16731434/314c87b9-8688-4d29-b0b9-67683d200121">

**Comment by vkmaxcooldude** [comment]
Hey @divyanshub024, could you assign this issue to me? I'd like to pick it up

**Comment by divyanshub024** [comment]
@vkmaxcooldude Done ✅
