### ISSUE TITLE
feat: Add support for the spacer widget.

### ISSUE THREAD

**Issue by divyanshub024** [Securrency-OSS/mirai#301]
**Description**

Add support for the spacer widget.

**Requirements**

- [ ] Add Mirai parser for the spacer widget

**Additional Context**

https://api.flutter.dev/flutter/widgets/Spacer-class.html

**Comment by uveshm003** [comment]
I want to work on this issue. I am having very good experience with similar project in which i worked with dynamic forms(forms and validation using Json).
