### ISSUE TITLE
feat: Add support for a PushNamed route

### ISSUE THREAD

**Issue by RodolfoSilva** [Securrency-OSS/mirai#79]
**Description**

Implement support for a pushNamedRoute method, which would allow users to navigate to existing pages without the need to recreate the page in the server. This would make it easier and more efficient for migrate an existent app to Mirai.

**Requirements**

- [ ] Push to a existent flutter router
- [ ] Push and replace to an existent flutter router
- [ ] Push and remove all previous page to an existent flutter router

**Comment by divyanshub024** [comment]
Hey @RodolfoSilva 👋🏻 

Thank you for your continuous contribution. This is something that we are planning to do in our upcoming releases. 

I want to clarify what do you mean by "navigate to existing pages without the need to recreate the page in the server"? Are these existing pages the SDUI pages or the CDUI pages, compiled with the app?

**Comment by RodolfoSilva** [comment]
CDUI pages.
