### ISSUE TITLE
feat: Add support for `appBarTheme` in `MiraiTheme`

### ISSUE THREAD

**Issue by i-asimkhan** [Securrency-OSS/mirai#83]
**Description**

Recently we have provided the `ThemeData` support through our own customized `MiraiTheme`. Now furthermore, we need to provide support for theme components.

For instance, the app bar component theme will look like this.

```
{
   'appBarTheme' : {
        'color' : '#ffffff',
         'backgroundColor' : '#4D00E9',
    }
}
```

**Comment by divyanshub024** [comment]
Hey @iamasimkhan, Let's divide this issue into multiple issues for each component theme. Like AppBarTheme, ElevatedButtonTheme etc.
