### ISSUE TITLE
feat: Add support for `floatingActionButtonTheme` in `MiraiTheme`

### ISSUE THREAD

**Issue by i-asimkhan** [Securrency-OSS/mirai#87]
**Description**

Recently we have provided the `ThemeData` support through our own customized `MiraiTheme`. Now furthermore, we need to provide support for theme components.

For instance, the floating action button component theme will look like this.

```
{
   'floatingActionButtonTheme' : {
        'color' : '#ffffff'
    }
}
```

**Comment by loud-at-heart** [comment]
@i-asimkhan @divyanshub024 Can you assign me this task?

**Comment by i-asimkhan** [comment]
> @i-asimkhan @divyanshub024 Can you assign me this task?

This has an open PR
